### ISSUE TITLE
SQL File

### ISSUE THREAD

**Issue by neizvelebiliziran** [iamareebjamal/car-rental-php#1]
Hello,

could you also share the SQL file of the project?

Regards

**Comment by iamareebjamal** [comment]
I formatted my PC after this project but I'll recreate the database and let you know in a couple of days

**Comment by neizvelebiliziran** [comment]
Ok, thanks a lot.

**Comment by melsonlyz** [comment]
Hi,
Could you upload the sql file of the project~?

**Comment by iamareebjamal** [comment]
I'm sorry, I digged but couldn't find the file. I'll recreate it in a few days if I get time

**Comment by melsonlyz** [comment]
Ok, looking for the good news.

**Comment by anvesh523** [comment]
Any luck !

**Comment by mzaboss** [comment]
any luck creating sql file?

**Comment by iamareebjamal** [comment]
SQL DDL and inserts are available in migrate_00.sql and migrate_01.sql respectively

**Comment by iamareebjamal** [comment]
Admin Username and password : `admin` `password`
