### ISSUE TITLE
compatible for mysql

### ISSUE THREAD

**Issue by tasoraso** [iamareebjamal/car-rental-php#2]
hi this code will be more compatible for new version of mysql have error with END and BEGINN but now is fixed.
DELIMITER $$
CREATE TRIGGER `STOCK_UPDATE_DECREASE` AFTER INSERT ON `transaction` FOR EACH ROW UPDATE `cars` SET `stock` = stock - 1 WHERE `_id` = NEW.car_id
$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER `STOCK_UPDATE_INCREASE` AFTER DELETE ON `transaction` FOR EACH ROW UPDATE `cars` SET `stock` = stock + 1 WHERE `_id` = OLD.car_id
$$
DELIMITER ;

one more thing:
did you plan something for pay and transaction.

**Comment by iamareebjamal** [comment]
Hi, thanks for heads up. Can you send a PR?

About pay and transaction, actually no because I made the site as a weekly assignment from college
