### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by surya5353** [iamareebjamal/car-rental-php#3]
When i execute **migrate_00.sql** error comes like below. is any version problem ?

Error
SQL query:

CREATE TABLE address(

_id INT PRIMARY KEY AUTO_INCREMENT ,
street VARCHAR( 100 ) NOT NULL ,
city VARCHAR( 100 ) NOT NULL ,
state VARCHAR( 100 ) NOT NULL ,
country VARCHAR( 100 ) NOT NULL ,
zip INT NOT NULL
);

MySQL said: Documentation

#1050 - Table 'address' already exists

**Comment by iamareebjamal** [comment]
Yes, you already have an address table, drop it and try again
