### ISSUE TITLE
Fatal error: Call to a member function prepare() on null

### ISSUE THREAD

**Issue by crynxmartinez** [iamareebjamal/car-rental-php#4]
![image](https://user-images.githubusercontent.com/25003081/47252809-0a15c700-d47d-11e8-84b0-9b5284700eb6.png)

Im using xammp. and I uploaded the sql. when I try to run the index. this error shows up. can you help me sir.
thank you.

**Comment by iamareebjamal** [comment]
As the error states, no database found
