### ISSUE TITLE
The header URL links do NOT WORKS

### ISSUE THREAD

**Issue by hereclit** [iamareebjamal/car-rental-php#5]
Hi , cannot access the url REGISTER , SINGIN , RENTALS from the header of the page.  No ones of the pages cannot found on http://mysite/xxxxxxxx 

I think is a route issue.  All the pages are in this location www/mysite/classes/pages/ .Can you help me with this? Thank you !

Not Found
The requested URL /register was not found on this server.

Apache/2.4.37 (Win32) PHP/7.2.14 Server at 10.164.55.94 Port 80

**Comment by iamareebjamal** [comment]
It's not a maintained project
